services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    _instanceof:
        EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\BaseWorker:
            calls:
                - [setNameHelper, ['@EzSystems\EzPlatformGraphQL\Schema\Domain\Content\NameHelper']]

        EzSystems\EzPlatformGraphQL\Schema\Worker:
            tags:
                - {name: 'ezplatform_graphql.domain_schema_worker'}

        EzSystems\EzPlatformGraphQL\Schema\Domain\Iterator:
            tags:
                - {name: 'ezplatform_graphql.schema_domain_iterator'}

    EzSystems\EzPlatformGraphQL\Schema\Builder\SchemaBuilder: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper:
        alias: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\DefaultFieldDefinitionMapper

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\DefaultFieldDefinitionMapper: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\ResolverVariables:
        decorates: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        decoration_priority: -5
        arguments:
            $innerMapper: '@EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\ResolverVariables.inner'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\ConfigurableFieldDefinitionMapper:
        decorates: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        arguments:
            $innerMapper: '@EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\ConfigurableFieldDefinitionMapper.inner'
            $typesMap: '%ezplatform_graphql.schema.content.mapping.field_definition_type%'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\RelationFieldDefinitionMapper:
        decorates: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        arguments:
            $contentTypeService: '@ezpublish.siteaccessaware.service.content_type'
            $innerMapper: '@EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\RelationFieldDefinitionMapper.inner'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\SelectionFieldDefinitionMapper:
        decorates: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        arguments:
            $innerMapper: '@EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\SelectionFieldDefinitionMapper.inner'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\AddItemOfTypeConnectionToGroup: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\AddItemToGroup: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\AddItemTypeToItemGroupTypes: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\AddItemTypeToItemTypeIdentifierList: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\DefineItem: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\DefineItemConnection: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\DefineItemMutation: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentType\DefineItemType: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentTypeGroup\AddDomainGroupToDomain: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentTypeGroup\DefineDomainGroup: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\ContentTypeGroup\DefineDomainGroupTypes: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\FieldDefinition\AddFieldDefinitionToItemMutation: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\FieldDefinition\AddFieldDefinitionToItemType: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\FieldDefinition\AddFieldValueToItem: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Worker\Language\AddLanguageToEnum: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\LanguagesIterator: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\NameHelper: ~

    Ibexa\GraphQL\Schema\Domain\NameValidator: ~

    EzSystems\EzPlatformGraphQL\Schema\Domain\ImageVariationDomain:
        calls:
            - method: setLogger
              arguments:
                  - '@logger'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\ContentDomainIterator:
        calls:
            - method: setLogger
              arguments:
                  - '@logger'

    EzSystems\EzPlatformGraphQL\Schema\Builder:
        alias: 'EzSystems\EzPlatformGraphQL\Schema\Builder\SchemaBuilder'

    EzSystems\EzPlatformGraphQL\Schema\Generator: ~

    EzSystems\EzPlatformGraphQL\Schema\ImagesVariationsBuilder: ~

    EzSystems\EzPlatformGraphQL\Schema\SchemaGenerator: ~
