services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand:
        arguments:
            $schemaRootDir: '%ezplatform.graphql.schema.root_dir%'
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\GraphQL\TypeDefinition\ContentTypeMapper: ~

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQueryMapper: ~
