services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand:
        arguments:
            $schemaRootDir: '%ezplatform.graphql.schema.ezplatform_dir%'
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQueryMapper: ~

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQuerySortByMapper: ~

    EzSystems\EzPlatformGraphQL\Security\NonAdminGraphQLRequestMatcher:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\NameHelper:
        arguments:
            $fieldNameOverrides: '%ezplatform_graphql.schema.content.field_name.override%'

    EzSystems\EzPlatformGraphQL\GraphQL\Mapper\ContentImageAssetMapperStrategy:
        arguments:
            $assetMapper: '@eZ\Publish\Core\FieldType\ImageAsset\AssetMapper'
            $contentLoader: '@EzSystems\EzPlatformGraphQL\GraphQL\DataLoader\CachedContentLoader'
        tags:
            - { name: ibexa.fieldtype.image_asset.mapper_strategy, priority: 0 }
