services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\Command\:
        resource: '../../Command/*'
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\GraphQL\TypeDefinition\ContentTypeMapper: ~

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQueryMapper: ~
