services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand:
        arguments:
            $schemaRootDir: '%ezplatform.graphql.schema.ezplatform_dir%'
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\QueryMapper:
        alias: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQueryMapper

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQueryMapper: ~

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQuerySortByMapper: ~

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\ContentCollectionFilterBuilder: ~

    EzSystems\EzPlatformGraphQL\Security\NonAdminGraphQLRequestMatcher:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory $currentSiteItemFactory: '@EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory\CurrentSite'

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory $relatedContentItemFactory: '@EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory\RelatedContent'

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory\CurrentSite:
        class: 'EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory'
        arguments:
            $locationGuesser: '@EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\LocationGuesser\CurrentSiteContent'

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory\RelatedContent:
        class: 'EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory'
        arguments:
            $locationGuesser: '@EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\LocationGuesser\RelatedContent'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\SiteaccessGuesser\SiteaccessGuesser:
        arguments:
            $siteAccessService: '@ezpublish.siteaccess_service'
            $configResolver: '@ezpublish.config.resolver'
            $provider: '@ezpublish.siteaccess.provider'
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    EzSystems\EzPlatformGraphQL\Schema\Domain\Content\NameHelper:
        arguments:
            $fieldNameOverrides: '%ezplatform_graphql.schema.content.field_name.override%'
