services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    _instanceof:
        BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\BaseWorker:
            calls:
                - [setNameHelper, ['@BD\EzPlatformGraphQLBundle\DomainContent\NameHelper']]

        BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\SchemaWorker:
            tags:
                - {name: 'ezplatform_graphql.domain_schema_worker'}

        BD\EzPlatformGraphQLBundle\Schema\SchemaBuilder:
            tags:
                - {name: 'ezplatform_graphql.schema_builder'}

    BD\EzPlatformGraphQLBundle\DomainContent\DomainContentSchemaBuilder: ~

    BD\EzPlatformGraphQLBundle\Schema\SchemaGenerator: ~

    BD\EzPlatformGraphQLBundle\DomainContent\RepositoryDomainGenerator:

    BD\EzPlatformGraphQLBundle\DomainContent\NameHelper: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\DefineDomainContent: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\AddDomainContentToDomainGroup: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentTypeGroup\DefineDomainGroup: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentTypeGroup\AddDomainGroupToDomain: ~

    BD\EzPlatformGraphQLBundle\DomainContent\FieldValueBuilder\BaseFieldValueBuilder: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\FieldDefinition\AddFieldDefinitionToDomainContent:
        arguments:
            $defaultFieldValueBuilder: '@BD\EzPlatformGraphQLBundle\DomainContent\FieldValueBuilder\BaseFieldValueBuilder'

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\AddContentTypeToContentTypeIdentifierList: ~

    BD\EzPlatformGraphQLBundle\DomainContent\FieldValueBuilder\RelationListFieldValueBuilder:
        tags:
            - {name: ezplatform_graphql.field_value_builder, type: 'ezobjectrelationlist'}

    BD\EzPlatformGraphQLBundle\DomainContent\FieldValueBuilder\SelectionFieldValueBuilder:
        tags:
            - {name: ezplatform_graphql.field_value_builder, type: 'ezselection'}

    BD\EzPlatformGraphQLBundle\Schema\ImagesVariationsBuilder: ~