<?php

namespace BD\EzPlatformGraphQLBundle;

use BD\EzPlatformGraphQLBundle\DependencyInjection\Compiler;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class BDEzPlatformGraphQLBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new Compiler\FieldValueTypesPass());
        $container->addCompilerPass(new Compiler\FieldValueBuildersPass());
        $container->addCompilerPass(new Compiler\SchemaWorkersPass());
        $container->addCompilerPass(new Compiler\SchemaBuildersPass());
    }
}
