<?php

namespace BD\EzPlatformGraphQLBundle;

use BD\EzPlatformGraphQLBundle\DependencyInjection\Compiler\FieldValueTypesPass;
use BD\EzPlatformGraphQLBundle\DependencyInjection\Compiler\RepositoryFromPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class BDEzPlatformGraphQLBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new FieldValueTypesPass());
    }
}
